### Sign Up (Devise User Creation)
POST http://localhost:3000/auth
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password",
  "password_confirmation": "password",
  "confirm_success_url": "YOUR_FRONT_END_URL"
}

### Sign In (Devise User Session Creation)POST http://localhost:3000/auth/sign_in
POST http://localhost:3000/auth/sign_in
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password"
}

###

### List Todos (Replace {{user_token}} and {{user_client}} with values from Sign In response)
GET http://localhost:3000/todos
Authorization: Bearer eyJhY2Nlc3MtdG9rZW4iOiJqenZMcHZVbDVEN2FaWjZETGV6QXR3IiwidG9rZW4tdHlwZSI6IkJlYXJlciIsImNsaWVudCI6IlFhMXplcF9SR2J2SzJzVTBjVEhRQXciLCJleHBpcnkiOiIxNjk2NDA4NDI5IiwidWlkIjoidGVzdEBleGFtcGxlLmNvbSJ9
uid: test@example.com
client: Qa1zep_RGbvK2sU0cTHQAw
# expiry: 1696408295


###

### Create a New Todo (Replace {{user_token}} and {{user_client}} with values from Sign In response)
POST http://localhost:3000/todos
Authorization: Bearer eyJhY2Nlc3MtdG9rZW4iOiJQWXdEbk5DSmtLSnZ3T3VPMTlUbTRnIiwidG9rZW4tdHlwZSI6IkJlYXJlciIsImNsaWVudCI6IkZxMzdQXzZER3ZpMG9faFpRaTlIZnciLCJleHBpcnkiOiIxNjk2NDA4Njk1IiwidWlkIjoidGVzdEBleGFtcGxlLmNvbSJ9
uid: test@example.com
client: Fq37P_6DGvi0o_hZQi9Hfw
Content-Type: application/json

{
  "title": "New Todo Item"
}

###
